application: test
version: 1
runtime: python
api_version: 1

handlers:

- url: /assets
  static_dir: assets

- url: /images
  static_dir: assets/images
  
- url: /scripts
  static_dir: assets/scripts
  
- url: /css
  static_dir: assets/css

- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

- url: /robots\.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: .*
  script: server.py
